### ISSUE TITLE
Error about main.py

### ISSUE THREAD

**Issue by huangjiancong1** [andrewliao11/gail-tf#18]
system: Ubuntu 16.04
GPU: Nvidia 1050Ti
CPU: I7
Mujoco version: pro150
ERROR:
When i start imitation learning,
after commanded: 
`python3 main.py --env_id $ENV_ID --expert_path $PICKLE_PATH`

The Mujoco simulator appeared, then the model appeared and everything was ok, but after 2 seconds, mujoco entered an unresponsive state（Stop running）.But the command terminal still running and calculating.  See the picture and terminal output below for details:

Screenshot
https://drive.google.com/open?id=1RKHxacZqvodmIOkBaNGxJcfmTdLOi6dO
https://drive.google.com/open?id=12_pbRtbtbwguY-j77LkVf6D4vsTHcBKX

Terminal:
```
********** Iteration 802 ************
Optimizing Policy...
sampling
done in 2.158 seconds
computegrad
done in 0.003 seconds
cg
      iter residual norm  soln norm
         0       2.15          0
         1       3.63      0.364
         2       3.73      0.821
         3       2.89       1.38
         4       3.28       2.06
         5       2.47       2.77
         6       2.56        3.4
         7       2.48       3.89
         8       1.57       4.48
         9       1.43       4.89
        10      0.906       5.23
done in 0.031 seconds
Expected: 0.311 Actual: 0.352
violated KL constraint. shrinking step.
Expected: 0.311 Actual: 0.163
Stepsize OK!
vf
done in 0.109 seconds
sampling
done in 2.047 seconds
computegrad
done in 0.003 seconds
cg
      iter residual norm  soln norm
         0       1.96          0
         1       2.97      0.438
         2       3.54      0.921
         3       3.14       1.53
         4       2.65       2.26
         5       2.46       2.92
         6       2.07       3.57
         7       1.96       4.11
         8       1.45       4.56
         9       1.23       4.97
        10      0.834       5.31
done in 0.031 seconds
Expected: 0.309 Actual: 0.331
violated KL constraint. shrinking step.
Expected: 0.309 Actual: 0.158
Stepsize OK!
vf
done in 0.110 seconds
sampling
done in 2.614 seconds
computegrad
done in 0.003 seconds
cg
      iter residual norm  soln norm
         0       2.34          0
         1       4.35      0.363
         2       3.25      0.842
         3       3.98       1.34
         4        3.3       1.87
         5       3.32       2.53
         6       3.49        3.1
         7       2.46        3.6
         8       1.99       4.21
         9       1.81       4.67
        10       1.21       5.13
done in 0.032 seconds
Expected: 0.314 Actual: 0.439
violated KL constraint. shrinking step.
Expected: 0.314 Actual: 0.180
Stepsize OK!
vf
done in 0.102 seconds
Optimizing Discriminator...
generator_loss |   expert_loss |       entropy |  entropy_loss | generator_acc |    expert_acc
   0.55519825 |     0.4537142 |    0.58335435 | -0.0005833544 |    0.70410156 |    0.82421875
----------------------------------
| EpLenMean       | 135          |
| EpRewMean       | 67.860306    |
| EpThisIter      | 8            |
| EpTrueRewMean   | 701          |
| EpisodesSoFar   | 7982         |
| TimeElapsed     | 5.97e+03     |
| TimestepsSoFar  | 821432       |
| entloss         | 0.0          |
| entropy         | 24.121952    |
| ev_tdlam_before | 0.846        |
| meankl          | 0.0051494665 |
| optimgain       | 0.17973988   |
| surrgain        | 0.17973988   |
----------------------------------

```

**Comment by huangjiancong1** [comment]
[Imitation Learning in Step 2](https://github.com/andrewliao11/gail-tf)

**Comment by huangjiancong1** [comment]
When i `ctrl+c` the Imitation Learning and start the next Step to evaluate it. The Mujoco were run about 2 seconds and the stop running almost the same as above.
:~/gail-tf$ `python main.py --env_id Humanoid-v2 --task evaluate --stochastic_policy "False" --load_model_path ./checkpoint/ppo.Humanoid.0.00/ppo.Humanoid.0.00-400 --expert_path ./stochastic.ppo.Humanoid.0.00.pkl` 
```
2018-09-07 18:24:04.276686: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-07 18:24:04.276988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.34GiB
2018-09-07 18:24:04.277019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-09-07 18:24:04.457938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-07 18:24:04.457985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-09-07 18:24:04.457991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-09-07 18:24:04.458160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 808 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
/home/huang/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Creating window glfw
100%|████████████████████████████████████████████████████████| 1500/1500 [00:00<00:00, 921825.05it/s]
Total trajectories: 1500
Total transitions: 192509
Average episode length: 128.339333
Average returns: 661.088659
WARNING:tensorflow:From /home/huang/venv/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-09-07 18:24:08.751992: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key adversary/fully_connected/biases not found in checkpoint
Traceback (most recent call last):
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key adversary/fully_connected/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 127, in <module>
    main(args)
  File "main.py", line 119, in main
    number_trajs=10, stochastic_policy=args.stochastic_policy)
  File "/home/huang/gail-tf/gailtf/algo/trpo_mpi.py", line 400, in evaluate
    U.load_state(load_model_path)
  File "/home/huang/gail-tf/gailtf/baselines/common/tf_util.py", line 280, in load_state
    saver.restore(get_session(), fname)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key adversary/fully_connected/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "main.py", line 127, in <module>
    main(args)
  File "main.py", line 119, in main
    number_trajs=10, stochastic_policy=args.stochastic_policy)
  File "/home/huang/gail-tf/gailtf/algo/trpo_mpi.py", line 400, in evaluate
    U.load_state(load_model_path)
  File "/home/huang/gail-tf/gailtf/baselines/common/tf_util.py", line 279, in load_state
    else: saver = tf.train.Saver()
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1311, in __init__
    self.build()
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1458, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/huang/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key adversary/fully_connected/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by andrewliao11** [comment]
if you get stuck for rendering in real-time, I suggest you record them as videos

**Comment by huangjiancong1** [comment]
How to do ?

**Comment by huangjiancong1** [comment]
My tensorflow version is 1.7, does this matter? Newer version? There have some same question.[https://github.com/KranthiGV/Pretrained-Show-and-Tell-model/issues/7](url)

**Comment by andrewliao11** [comment]
from the code [here](https://github.com/openai/gym/blob/master/gym/envs/mujoco/mujoco_env.py#L108-L116), you can get the image of the current environment. 
In case that you are not familiar with converting images to video, here a snippet of it
```python
import imageio

writer = imageio.get_writer('~/output.mp4', fps=fps)
for image in images_list:
    writer.append_data(image)
writer.close()
```

**Comment by andrewliao11** [comment]
i'll first close the issue here. feel free to re-open it
